name:                optimization-project
version:             0.1.0.0
github:              "vacbo/optimization-project"
license:             BSD-3-Clause
author:              "Vacbo"
maintainer:          "example@example.com"
copyright:           "2025 Vacbo"

extra-source-files:
- README.md
- CHANGELOG.md

flags:
  profiling:
    description: Enable profiling
    manual: True
    default: False

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/vacbo/optimization-project#readme>

dependencies:
- base >= 4.7 && < 5
- aeson
- directory
- filepath
- cassava
- bytestring
- vector
- vector-algorithms
- text
- time
- containers
- unordered-containers
- random
- mwc-random
- parallel
- async
- deepseq
- mtl
- transformers
- hashable
- stm

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints
- -O2
- -funbox-strict-fields
- -fexcess-precision
- -optc-O3
- -optc-ffast-math

library:
  source-dirs: src
  ghc-options:
  - -O2
  - -funbox-strict-fields
  - -fexcess-precision
  - -optc-O3
  - -optc-ffast-math
  when:
  - condition: flag(profiling)
    ghc-options: []

executables:
  optimization-project-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -funbox-strict-fields
    - -fexcess-precision
    - -optc-O3
    - -optc-ffast-math
    dependencies:
    - optimization-project
    when:
    - condition: flag(profiling)
      ghc-options:
      - -fprof-auto

tests:
  optimization-project-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - optimization-project
